language: node_js
node_js:
  - "8.11.3"
cache:
  directories:
    - elm-stuff
install:
  - npm install -g elm@0.18.0
  - elm-package install -y
script:
  - elm-make src/Normal.elm --output=fsstats.js --warn
